Drop TABLE clientes;


CREATE TABLE IF NOT EXISTS clientes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created TIMESTAMP not null,
    updated TIMESTAMP not null,
    status CHAR(1) default(1) not null,
    fname VARCHAR(50) Not null,
    lname VARCHAR(50) Not null,
    address TEXT NOT NULL, 
    birthdate DATE Not Null
);


DROP function Registrar;
DROP function ConsultarPorID;
DROP function Actualizar; 

CREATE function Registrar
(
nombres varchar,
apellido varchar,
direccion text,
nacimiento date 
) returns void language plpgsql as
$$
Begin
 Insert into clientes values (default,current_timestamp,current_timestamp,1, nombres,apellido, direccion,nacimiento);
End;
$$;

CREATE function ConsultarPorID
(
codigo integer
)
 returns void language plpgsql as
$$
Begin
 Select * from clientes where id=codigo;
End;
$$;

CREATE function Actualizar
(
codigo integer,
nombres varchar,
apellido varchar,
direccion text,
nacimiento date 
)
 returns void language plpgsql as
$$
Begin
 UPDATE clientes SET updated=current_timestamp, fname=nombres,lname=apellido, address=direccion,birthdate= nacimiento where id=codigo;
End;
$$;


Select Registrar('nombres','apellido','direccion','2000-04-05')
